// Code generated by goctl. DO NOT EDIT.
package types

type ArticleItem struct {
	Id         string `json:"id"`
	Title      string `json:"title"`
	Desc       string `json:"desc"`
	Content    string `json:"content"`
	Author     string `json:"author"`
	Assets     string `json:"assets"`
	Status     int64  `json:"status"`
	CreateTime int64  `json:"createTime"`
}

type CommentItem struct {
	Id         string `json:"id"`
	Pid        string `json:"pid"`
	Aid        string `json:"aid"`
	Content    string `json:"content"`
	Creator    string `json:"creator"`
	CreateTime string `json:"createTime"`
}

type CommonResp struct {
	Status int64  `json:"status"`
	Msg    string `json:"msg"`
}

type CreateArticleReq struct {
	Title   string `json:"title"`
	Desc    string `json:"desc"`
	Content string `json:"content"`
	Assets  string `json:"assets"`
	Status  int64  `json:"status"`
}

type CreateArticleResp struct {
	Status int64  `json:"status"`
	Msg    string `json:"msg"`
	Id     string `json:"id"`
}

type CreateCommentReq struct {
	Pid     string `json:"pid"`
	Aid     string `json:"aid"`
	Content string `json:"content"`
}

type CreateCommentResp struct {
	Status int64  `json:"status"`
	Msg    string `json:"msg"`
}

type DeleteArticleReq struct {
	Id string `json:"id"`
}

type DeleteCommentReq struct {
	Id string `json:"id"`
}

type GetArticleDetailReq struct {
	Id string `path:"id"`
}

type GetArticleDetailResp struct {
	Status int64       `json:"status"`
	Msg    string      `json:"msg"`
	Data   ArticleItem `json:"data"`
}

type GetArticleListReq struct {
	Page int64 `json:"page"`
	Size int64 `json:"size"`
}

type GetArticleListResp struct {
	List  []ArticleItem `json:"list"`
	Total int64         `json:"total"`
}

type GetCommentByAidReq struct {
	Aid string `path:"aid"`
}

type GetCommentByAidResp struct {
	List  []CommentItem `json:"list"`
	Total int64         `json:"total"`
}

type GetCommentByPidReq struct {
	Pid string `path:"pid"`
}

type GetCommentByPidResp struct {
	List  []CommentItem `json:"list"`
	Total int64         `json:"total"`
}

type UpdateArticleReq struct {
	Id      string `json:"id"`
	Title   string `json:"title"`
	Desc    string `json:"desc"`
	Content string `json:"content"`
	Assets  string `json:"assets"`
	Status  int64  `json:"status"`
}

type UpdateArticleResp struct {
	Status int64  `json:"status"`
	Msg    string `json:"msg"`
}

type UploadImageInfo struct {
	Url  string `json:"url"`
	Alt  string `json:"alt"`
	Href string `json:"href"`
}

type UploadImageReq struct {
	File    []byte `json:"file"`
	Type    string `json:"type"`
	UnionID string `json:"unionId"`
}

type UploadImageResp struct {
	Errno   int64           `json:"errno"`
	Data    UploadImageInfo `json:"data"`
	Message string          `json:"message"`
}
